# Generated by Django 2.2.7 on 2021-01-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytanie',
            name='odp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
