# Generated by Django 2.2.7 on 2021-01-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_pytanie_odp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pytanie',
            name='odp',
        ),
    ]
