# Generated by Django 2.2.7 on 2021-01-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_tworca'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='opis',
            field=models.CharField(default='opis', max_length=500),
            preserve_default=False,
        ),
    ]
