# Generated by Django 2.2.7 on 2021-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytanie',
            name='opcja1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pytanie',
            name='opcja2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pytanie',
            name='opcja3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pytanie',
            name='opcja4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pytanie',
            name='pytanie',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opis',
            field=models.CharField(max_length=1000),
        ),
    ]
